apiVersion: v1
kind: Service
metadata:
  name: user-authentication-server-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: user-authentication-server-app
